### ISSUE TITLE
Not able to install this plugin on project targeting capacitor 4.1

### ISSUE THREAD

**Issue by najmulansari** [dragermrb/capacitor-plugin-file-opener#4]
Hi there,
I am not able to install this plugin on the project targeting capacitor 4.1. While installing itself it's getting failed.

Below are the environment details:
Windows: 11
Ionic: 6.2
Angular: 14.2

Please update the plugin to support the latest version of the capacitor.

**Comment by dragermrb** [comment]
Hi @najmulansari!

We are working on it. We will publish a version as soon as possible.

**Comment by dragermrb** [comment]
Can you try last beta version?

`npm i @whiteguru/capacitor-plugin-file-opener@4.0.2-beta.1`

**Comment by najmulansari** [comment]
Thank you so much, I am able to install it now. Please let me know when you have the release version available.

**Comment by sreejith-mv** [comment]
@dragermrb,Can you please release this? Beta is working great with latest capacitor and ionic versions..

**Comment by dragermrb** [comment]
Done!
