### ISSUE TITLE
Import plugin to a project

### ISSUE THREAD

**Issue by razorback21** [dragermrb/capacitor-plugin-file-opener#5]
Hi,

Can you show an example how to import the plugin? If you can provide an example how setup the plugin that would be great.

**Comment by dragermrb** [comment]
Hi!

This plugin only have one method `open()`. You only need to pass a local file path:

```ts
import { FileOpener } from '@whiteguru/capacitor-plugin-file-opener';

const my_file_local_path = 'some-file-path.pdf';

FileOpener.open({
  path: my_file_local_path,
});
```

**Comment by razorback21** [comment]
Thanks. Will it work with remote file url?

Sent from Yahoo Mail on Android 
 
  On Thu, 9 Mar 2023 at 3:17 pm, Manuel ***@***.***> wrote:   


Hi!

This plugin only have one method open(). You only need to pass a local file path:
import { FileOpener } from ***@***.***/capacitor-plugin-file-opener';

const my_file_local_path = 'some-file-path.pdf';

FileOpener.open({
  path: my_file_local_path,
});

**Comment by dragermrb** [comment]
You can try, but I don't think so...
