### ISSUE TITLE
Support Capacitor 6

### ISSUE THREAD

**Issue by kientrant1** [dragermrb/capacitor-plugin-file-opener#7]
[Capacitor 6](https://ionic.io/blog/announcing-capacitor-6-0) has been announced and released. Do we have any chance to adapt? Many thanks!

**Comment by dragermrb** [comment]
Maybe next week...

**Comment by dragermrb** [comment]
Version v6.0.1 released

https://github.com/dragermrb/capacitor-plugin-file-opener/releases/tag/v6.0.1
